apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../helm/templates/deployment.yaml
  - ../../helm/templates/service.yaml

replicas:
  - name: myapp
    count: 1

images:
  - name: myapp
    newTag: dev-latest

commonLabels:
  environment: dev

patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "100m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "128Mi"
    target:
      kind: Deployment
      name: myapp
